version: "3.9"
services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    environment:
      POSTGRES_DB: "gophermart"
      POSTGRES_USER: "gopher"
      POSTGRES_PASSWORD: "G0ph3R"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - 5432:5432
  gophermart:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: gophermart
    ports:
      - 8080:8080
    depends_on:
      - postgres